### ISSUE TITLE
bug with TSIG verification of large responses

### ISSUE THREAD

**Issue by frankarinnet** [dnsjava/dnsjava#295]
We've encountered a bug with how DNSJAVA verifies the transaction signature of large responses.

In our environment, we can successfully perform an AXFR for a small zone (22 line zone file, 2096 bytes on the wire).  But we get a TSIG related error (org.xbill.DNS.ZoneTransferException: TSIG failure: BADSIG) when transferring a larger zone (7855 line zone file,  400k on the wire).

This bug was introduced between versions 3.1.0 and 3.20.  The TSIG class saw a significant rework there, and the interactions between the TSIG.StreamVerifier class and the TSIG.verify() method were broken then -- although seemingly only in cases where the signed response encompassed multiple messages.

While investigating this, we developed a patch for 3.5.2 this that we would be happy to submit as a pull request (or, really, help get this fixed some other way).

**Comment by ibauersachs** [comment]
Thanks for the report. Since you already have a patch, opening a PR would be super helpful.

**Comment by frankarinnet** [comment]
Willdo.  I'll get it submitted properly on Monday.

**Comment by frankarinnet** [comment]
Pull request submitted, but I need some guidance on a few points.  I've marked them in the pull request with some TODOs.

I tested the code, though against responses of various sizes (1 message in length, 50some messages in length, and 300+ messages in length).

**Comment by frankarinnet** [comment]
A few more notes.  The 3.2.0 version -- though bugged -- seemed to want HMAC signing logic moved out of the StreamVerifier class and into the TSIG.verify() method.

I have followed that in my changes, but it results in some extra conditional logic in the TSIG.verify() method.  Seeing the result, I'm a bit ambivalent.

If the maintainers decide they dislike the "everything goes in TSIG.verify()" method, I have a version which keeps more logic in the StreamVerifier class.

**Comment by ibauersachs** [comment]
Thanks again! Would you mind just posting the alternative here or in a separate PR? It doesn't need to be pretty!

**Comment by frankarinnet** [comment]
Pull request for alternate approach (https://github.com/dnsjava/dnsjava/pull/297) posted.

**Comment by frankarinnet** [comment]
Added PR for main approach that properly targets 3.5.x branch: https://github.com/dnsjava/dnsjava/pull/298

(obseletes https://github.com/dnsjava/dnsjava/pull/296)

**Comment by frankarinnet** [comment]
Added program (https://github.com/frankarinnet/axfr/blob/main/README.md) to help with manual testing.

Still working on unit test, quite tricky for us.  Might have something tomorrow.

**Comment by frankarinnet** [comment]
A bit more information on the bug: _it turns out the current (bugged) implementation DOES work for some large responses_.

If the response includes a TSIG with each message, the current implementation validates it correctly.
While DNS servers are ALLOWED to build responses that way, they are not REQUIRED to do it that way.

DNS servers are only REQUIRED to put a TSIG on one out of 99? 100? messages (and always on the last message).

It is this last case that my PR addresses.

**Comment by frankarinnet** [comment]
With some help, I was able to generate a test that demonstrates the large response bug.

Unfortunately, it required a few changes to the TSIG.generate() method.  I don't know if we actually want those changes applied as-is, but this is the simplest approach for now.

The test changeset has been applied to the main PR: https://github.com/dnsjava/dnsjava/pull/298.
Also, in case it helps with testing, we created a PR that only contains the test: https://github.com/dnsjava/dnsjava/pull/299 (which should be easy to move between branches).

**Comment by frankarinnet** [comment]
There are still some TODOs which some decisions.  But I believe the substantial technical work is now done.  Let me know if/when we can help further.

**Comment by ibauersachs** [comment]
I haven't had time to look at the code yet, I'll try to have a look this weekend (but no promises). Thanks a lot for all the investigations and reproducers so far!

**Comment by ibauersachs** [comment]
I looked at both versions and opted for a mix of both. Also, I think I now understand why that `sharedHmac` field was there in the first place. I've opened a #300 that attempt to simplify your implementations. Are you okay with that or would you prefer to update one of your own PRs so that you're more visible as the author?

Can you please test if these changes work against the server you're using? I was unable to test against an actual server as both BIND and PowerDNS with a large example zone sign every message (as is required by [RFC8945, 5.3.1](https://www.rfc-editor.org/rfc/rfc8945.html#section-5.3.1)

**Comment by frankarinnet** [comment]
1. Please proceed without worrying about our visibility as authors.  We'll give your code a quick review on Monday.
2. Regarding the RFC: that's an interesting little hole that we fell into.
3. I'll give this a pretty thorough testing tomorrow (Monday) against our environment, and post the results here.

**Comment by frankarinnet** [comment]
Putting further comments on #300

**Comment by frankarinnet** [comment]
PR #300 still not verifying successfully.  Added PR #301 with one suggested way of fixing it.

**Comment by ibauersachs** [comment]
Thanks for the update. Not sure if I have time to work on it again this week, but I'll try. 

By any chance, can you add an actual conversation between dnsjava and a server, including the key, to this issue? It would help a lot with debugging and for the unit tests (to avoid testing against ourselves, which is now the obvious cause of the symmetrical problem in generate/verify).
If not, do you know a server product that I could install that still behaves pre-RFC8945?

**Comment by frankarinnet** [comment]
I can do something like this:
- configure the DNS server with a few different-sized zones with dummy data
- configure those zones with a just-for-this-test TSIG key
- and dump the associated TCP streams.

I'll have to lean on some folks to make the configuration changes, so it won't be tomorrow.  Say, by the end of the week.

**Comment by ibauersachs** [comment]
> I can do something like this:
>     * configure the DNS server with a few different-sized zones with dummy data
>     * configure those zones with a just-for-this-test TSIG key
>     * and dump the associated TCP streams.
> I'll have to lean on some folks to make the configuration changes, so it won't be tomorrow. Say, by the end of the week.

That would help! And end of week is plenty of time. Is the product you're using something I could install myself or is this internal ARIN code? If I could set this up myself you wouldn't need to involve other people or modify production systems.

I just pushed some changes to #300, not sure if they're enough.

**Comment by frankarinnet** [comment]
**re:  the new changeset:** works like a charm for the battery of tests I've been using.  We'll test it more completely over this week, but I'm pretty sure we're good.

**re: our setup:** that's a reasonable question, but those are some production-y details about our internal systems.  That, I'll have to ask for permission about that tomorrow (and probably email you offline).  Either way, I'll see what I can do.

**Comment by frankarinnet** [comment]
Left a few (very minor) comments as a code review on the #300 PR.  Big picture though, we're good to go!

Thank you very much for your hard work in getting this change in!

We'll still be testing this over the course of the week.  And I'll still have some TCP stream dumps by the end of the week.

**Comment by frankarinnet** [comment]
I've attached an ZIP
[large_response.zip](https://github.com/dnsjava/dnsjava/files/13231715/large_response.zip)
 with the TCP stream dump for dummy large zone (its just a bunch of text records).  The associated TSIG key is also inside.

**Comment by ibauersachs** [comment]
I added a test with the sample stream in #300 and I could also replicate the error and fix with the setup you sent me privately.
